### ISSUE TITLE
pescado

### ISSUE THREAD

**Issue by Jared-gtz** [Jared-gtz/pescado#1]
el animal es muy lindo es un animal no es salvaje 
es un animal que respira oxigeno y vuela por los aires
que animal será?
![tiburon-blanco](https://user-images.githubusercontent.com/42589815/44555800-906f9000-a6fc-11e8-8ef8-276f0d2056a4.jpg)
describe y corrige si esta bien o no lo mencionado de dicho animal

**Comment by bgleyva3** [comment]
La foto del animal y la descripción no concuerdan.
Sugeriría cambiar la foto por la de un **pajaro** como la que muestro a continuación:

![503805_1](https://user-images.githubusercontent.com/42397412/44561183-041f9600-a719-11e8-8984-4cc646357c34.jpg)

**Comment by bgleyva3** [comment]
He respondido a la pregunta de tu poema. Te dejo el commit hash para que lo veas:

6fefb35e3e2ba899953291db826950105d91e999
